language: node_js
node_js:
  - 5.1
cache:
  directories:
    - elm-stuff/build-artifacts
    - tests/elm-stuff/build-artifacts
install:
  - npm install -g elm@0.17.0
  - ./download-dependencies.sh .
  - ./download-dependencies.sh tests
script:
  - ./build.sh
  - ./test.sh
after_success:
  - ./deploy.sh
